### ISSUE TITLE
Multiple Monitors: Taskbar menu only works on one monitor

### ISSUE THREAD

**Issue by redfox05** [abhishekbanthia/Clocker#9] opened 2016-09-01 17:01 UTC
Not as important as the CPU issue, but thought I would mentioned it for you.

When using multiple monitors, in my case 1 external with my Macbook Pro 15", Clocker does not seem to want to open when I click the icon on my external monitor. When I click the icon on my Macbook screen taskbar, it does successfully open and work as expected.

The exact behaviour on the external monitor is that you click the clocker icon on the taskbar and a menu flashes up briefly, then looks like its being dragged away to the other monitor, but then just disappears.

**Comment by abhishekbanthia** [comment] 2016-09-01 21:40
This is something new. Investigating.

**Comment by dodekeract** [comment] 2016-10-05 21:29
For me this works, but only on 3 out of 4 screens.

My configuration is `[4*] [3*] [1*] [2]`
Where `[1]` is my main display, `*` means it's working as intended.
On my screen `[2]` the menu opens on screen `[1]` instead of `[2]`.

It is dragged to the left too, but stays on the screen, nearly exactly in the top right corner.

**Comment by phamann** [comment] 2017-04-26 15:14
This still seems to be an issue on Sierra. Unlike the previous posters, the menu doesn't flash or appear somewhere else when the icon is clicked on the secondary screen it just does nothing. It only works when the icon is clicked on the 1st screen.

Any update for a fix? Thanks for a great tool!

**Comment by abhishekbanthia** [comment] 2017-05-02 01:03
Guys, the new version attempts to fix this issue. Clocker should open on the monitor where the click takes place. Let me know how it goes.

**Comment by abhishekbanthia** [comment] 2017-05-02 15:32
Closing.

**Closed by abhishekbanthia** 2017-05-02 15:32 UTC
