### ISSUE TITLE
Clocker seems to continually run at 26-30% CPU on Macbook Pro

### ISSUE THREAD

**Issue by redfox05** [abhishekbanthia/Clocker#8] opened 2016-09-01 16:54 UTC
Hi there,

I just bought a brand new macbook pro, and did a backup migration from my iMac. I notice the fan is going like crazy most of the time, for several days now, which did not happen on my old Late 2013 Model Macbook Pro, so I did some digging. Activity Monitor is showing that Clocker is constantly using 26-30% of my CPU. Not just occasionally, ALL the time.

I can say say that right now the fan has finally calmed down and I cant hear it as such anymore, but the Activity Monitor still shows the CPU very high. Right now it has dropped briefly to 25.9% but ah back up to between 26-28% as we speak. The fan noises seem to be worse when its around 30%.

Spec:
  OS X Version:       El Capitan 10.11.6
  Model Name:   MacBook Pro 15-inch Mid 2015
  Model Identifier: MacBookPro11,5
  Processor Name:   Intel Core i7
  Processor Speed:  2.8 GHz
  Number of Processors: 1
  Total Number of Cores:    4
  L2 Cache (per Core):  256 KB
  L3 Cache: 6 MB
  Memory:   16 GB 1600 Mhz DDR3

If you need any more info, please let me know.

**Comment by redfox05** [comment] 2016-09-01 16:57
I saw the other thread you mentioned a timer. Can you tell me what the timer is used for? Can you add an option to change the polling frequency if its checking something?

**Comment by abhishekbanthia** [comment] 2016-09-01 21:31
Thank you for your feedback, @redfox05, and apologies for the issue you're facing.

You are correct, there's a timer to update the menu-bar icon interface, which is fired regularly. I have actually found an alternative method to achieve this using the `dispatch_after` method, which is much more efficient and memory friendly (tested this using Instruments), which will be implemented in the next version.

**Comment by redfox05** [comment] 2016-09-01 22:38
Ah thats sounds great. Thanks for the fast reply. Do you know when you will be able to release the new version/how long the app validation will take in the app store?

**Comment by dodekeract** [comment] 2016-09-11 13:58
Having the same issue, 25% on an i7 4790k.

**Comment by abhishekbanthia** [comment] 2016-09-12 16:27
Update: I'm swamped by work, but I will try to upload an unsigned build of the app (that attempts to fix this issue) by the end of the week.

**Comment by abhishekbanthia** [comment] 2016-09-18 20:09
Attached an unsigned copy which uses a different mechanism to update the menubar. Let me know how does this work for you:

(This has been tested only on my machine. So bear with me if it still does not fix the energy consumption issue)

[Clocker.zip](https://github.com/abhishekbanthia/Clocker/files/478964/Clocker.zip)

**Comment by dodekeract** [comment] 2016-09-19 01:13
@abhishekbanthia Didn't change anything. Can't you just update it once a minute?!? There's no need for what appears to be constant updates.

**Comment by abhishekbanthia** [comment] 2016-09-19 03:04
Attached a version that updates every 60 seconds. My reasoning is it can affect the accuracy of the time being shown, however so slightly:

[Clocker.app.zip](https://github.com/abhishekbanthia/Clocker/files/479185/Clocker.app.zip)

**Comment by dodekeract** [comment] 2016-09-19 03:58
@abhishekbanthia Thanks, I'll test that one. How did you previously manage updates? Everything above a second is overkill. Also, you may be able to fix the 60s issue by just starting the first timer after `secondsLeftUntilNextMinute` or something similar.

**Comment by dodekeract** [comment] 2016-09-19 04:00
Wow, it actually seems to be something else. I'm still getting 22% CPU usage. I don't know what causes this, but it **doesn't** seem to be the updates.

**Comment by dodekeract** [comment] 2016-09-19 04:00
@abhishekbanthia Can you reproduce this on your machine or does this not happen for you? If no, can I somehow help you to find the cause?

**Comment by abhishekbanthia** [comment] 2016-09-19 05:41
I actually - after trying multiple times - see the maximum energy consumption at 8%. It's quite interesting especially since I am testing it on a MacbookPro as well. Instruments show low energy consumption as well. Investigating other causes.

**Comment by dodekeract** [comment] 2016-09-19 06:07
@abhishekbanthia As I have a hackintosh workstation, I actually don't see the energy consumption. Make sure to look into pure CPU load too. There should be a correlation but it's probably a little bit different.

**Comment by abhishekbanthia** [comment] 2016-10-05 17:41
Question: Do any of you guys use dual screens?

**Comment by dodekeract** [comment] 2016-10-05 17:45
Yes, I'm using 4 screens right now.

**Comment by redfox05** [comment] 2016-10-05 21:12
@abhishekbanthia Yep I'm using 2 external monitors in addition to my 15" Macbook Pro screen

**Comment by redfox05** [comment] 2016-10-05 21:14
Regrettably I have had to uninstall your app until this is fixed, but happy to try again later.

**Comment by dodekeract** [comment] 2016-10-05 21:22
@abhishekbanthia I guess you found the real issue. 🙂

**Comment by redfox05** [comment] 2016-10-05 21:27
@dodekeract whats the real issue you are referring to? The dual screens?

**Comment by dodekeract** [comment] 2016-10-05 21:32
@redfox05 Yes, it seems that everyone affected by this has multiple displays. Since @abhishekbanthia asked if we have multiple displays, it seems that he found out what the issue is.

**Comment by dodekeract** [comment] 2016-10-05 21:36
@SashaOv @ry29 @prokher Are you using multiple displays? Everyone we've asked so far has multiple screens.

**Comment by abhishekbanthia** [comment] 2016-10-06 03:21
Yep, @dodekeract; looks like issue arises because of multiple displays.

**Comment by prokher** [comment] 2016-10-06 08:21
Yes I typically use two screens: laptop’s plus external one.

**Comment by ry29** [comment] 2016-10-06 11:25
yes, I have 3 displays. MacBook's, and 2 monitors via hdmi and thunderbolt.

**Comment by russelltrafford** [comment] 2016-10-06 16:35
Hmm, so where does this leave things? Having multiple monitors without Clocker installed has left my Macbook totally silent from fans and thus increasing CPU. So in itself multiple monitors is not a cause. It could be something we all have in common, but what will that mean in terms of why the app increased its CPU usage? Once we know that, hopefully a solution could then be found from that?

**Comment by dodekeract** [comment] 2016-10-06 16:49
I am quite sure this is because of the multiple times Clocker has to render. There's most likely something wrong in the part of code that determines this, which causes it to loop indefinitely on a multi screen machine.

**Comment by russelltrafford** [comment] 2016-10-13 15:42
Hey there. Quick update from me, ive now been able to test both your unsigned versions that were provided by you above.

The first one ran at around 40% CPU for me, with 2 externals monitors, and the macbook monitor running. See screenshot:
<img width="788" alt="screen shot 2016-10-13 at 8 37 40 am" src="https://cloud.githubusercontent.com/assets/22302818/19355874/c2548498-9120-11e6-8815-74a81dc2294d.png">

The second version you provided which updates every 60 seconds, runs at around 40-43% CPU. See screenshot:
<img width="797" alt="screen shot 2016-10-13 at 8 39 15 am" src="https://cloud.githubusercontent.com/assets/22302818/19355915/ddd3b8b0-9120-11e6-9c33-1c7b7bb9ec2d.png">

Let me know if I can check or test anything else for you. Apologies that it took me this long to test your unsigned updates, its just very hectic right now :P

**Comment by redfox05** [comment] 2016-10-13 15:44
Hey there. Quick update from me, ive now been able to test both your unsigned versions that were provided by you above.

The first one ran at around 40% CPU for me, with 2 externals monitors, and the macbook monitor running. See screenshot:
<img width="788" alt="screen shot 2016-10-13 at 8 37 40 am" src="https://cloud.githubusercontent.com/assets/7571495/19356026/3b3e3840-9121-11e6-96bc-cefb73fe47d5.png">


The second version you provided which updates every 60 seconds, runs at around 40-43% CPU. See screenshot:
<img width="797" alt="screen shot 2016-10-13 at 8 39 15 am" src="https://cloud.githubusercontent.com/assets/7571495/19356033/3f283528-9121-11e6-8c03-02c4a1b8661a.png">
Maybe they both run at the same approx, I maybe did not leave the first one running long enough.

Let me know if I can check or test anything else for you. Apologies that it took me this long to test your unsigned updates, its just very hectic right now :P

**Comment by andrewshubin** [comment] 2016-10-20 02:27
Indeed, the problem is with multiple monitors.
I have 21% of CPU with two monitors. When the second monitor is detached, it drops down to 0.3%.

**Comment by andrewshubin** [comment] 2016-10-20 02:30
Also, if I turn off the "Favorite" flag, it drops down to 0.0%, even with two monitors.

**Comment by redfox05** [comment] 2016-10-20 15:43
@andrewshubin correct, it does seem to be to do with the Favourite feature. I presume this is because the issue here is the updating of the time in the menu bar, and how it does this, which causes the CPU usage to increase. If the favourite option is disabled, the time is not shown on the menu bar, and thus no 'extra' CPU load.

**Comment by redfox05** [comment] 2016-10-20 15:45
@abhishekbanthia I wonder if you are able to restrict the time to showing on just **one monitor**, this may not be ideal for some people, but it could be an interim fix to prevent the CPU load? Maybe add it as a checkbox in the config? But would that reduce the CPU load?

**Comment by dodekeract** [comment] 2016-10-20 16:07
There is no way this isn't possible to show on all screens. It's 100% just inefficient code with an accidental loop.

**Comment by Palid** [comment] 2016-11-03 11:25
+1 For dual screen problem. Almost no usage on single screen, up to 35-40% cpu on dual screen (macbook pro mid 2012).

**Comment by abhishekbanthia** [comment] 2016-11-03 20:02
@Palid are the displays mirrored?

**Comment by Palid** [comment] 2016-11-03 21:20
@abhishekbanthia Nope.

**Comment by dodekeract** [comment] 2016-11-03 22:43
I'm extending to all 4 screens. No mirroring at all.

**Comment by SashaOv** [comment] 2016-11-04 16:16
Dual screen here as well, at least part of time

**Comment by abhishekbanthia** [comment] 2016-11-04 19:33
Ran a time profiler, and much of the problem lies with the recursive calling of menu bar's drawRect:

![screen shot 2016-11-04 at 12 47 25 pm](https://cloud.githubusercontent.com/assets/8280282/20019690/be0653d2-a28a-11e6-90bb-ed8207c3702a.png)

**Comment by abhishekbanthia** [comment] 2016-11-04 19:34
I have spent the much of yesterday and today debugging/fixing this and my changes are showing positive results (**0.8% CPU utilization** - tested with my MacBook Pro and external Thunderbolt monitor).

I'll attach a build after running some tests.

**Comment by dodekeract** [comment] 2016-11-04 20:55
@abhishekbanthia Something like this is exactly what I imagined would be the problem. Hope that fixes it for everyone.

**Comment by abhishekbanthia** [comment] 2016-11-04 21:30
Let me know if it works for you guys:


[Clocker.app.zip](https://github.com/abhishekbanthia/Clocker/files/572687/Clocker.app.zip)

**Comment by dodekeract** [comment] 2016-11-04 21:51
@abhishekbanthia Seems to be a lot better. It's down to `2.2%` CPU on my `i7-6700k`. I'm not sure if that's really needed, but it surely is bearable now. :smile:

**Comment by redfox05** [comment] 2016-11-04 22:06
@abhishekbanthia, I can confirm this takes it down to variations around 0.8-3% 

However, there seems to issues where when you open the menu it opens on another screen, sometimes under the clock on another screen, and sometimes even halfway down another screen. Currently using macbook screen and 2 external monitors, so 3 in total.

**Comment by dodekeract** [comment] 2016-11-04 22:09
@redfox05 Good point. I actually didn't test that menu. It looks *really* weird for me.

![screen shot 2016-11-04 at 11 08 55 pm](https://cloud.githubusercontent.com/assets/1133858/20023987/b74fb0b6-a2e3-11e6-9133-b8edc3554ce5.png)

**Comment by abhishekbanthia** [comment] 2016-11-04 22:17
Ah, @dodekeract positive that _restarting/moving to Applications_ fixed the weird appearances as well as the high energy usage?

**Comment by redfox05** [comment] 2016-11-04 22:56
I already had it stored in /Applications, but I tried a restart of the application which did not help.
Also tried uninstall, open from Downloads, then close, then move to Applications, and then open again, and it still did not fix the issue. Menu still opens in random places on alternative screens.

**Comment by dodekeract** [comment] 2016-11-04 23:17
@abhishekbanthia Either restarting or moving fixed it. I did both at the same time so I don't really know. My guess would be restarting.

**Comment by redfox05** [comment] 2016-11-04 23:28
Here are my screenshots if they help, the white box is just me blanking out my username.

In each test, the menu opens on screen 1.
Screen 1: Left external
Screen 2: Center external
Screen 3: Right macbook pro retina

Open from screen 1 clock:
![open-from-screen1-shows-on-screen1](https://cloud.githubusercontent.com/assets/7571495/20025437/8e957a58-a2ab-11e6-93c4-d11d4442e787.png)

Open from screen 2 clock:
![open-from-screen2-shows-on-screen1](https://cloud.githubusercontent.com/assets/7571495/20025442/9736165e-a2ab-11e6-8e75-8a5f705e5173.png)


Open from screen 3 clock:
![open-from-screen3-shows-on-screen1](https://cloud.githubusercontent.com/assets/7571495/20025446/a02bc8d0-a2ab-11e6-8003-4406758861f4.png)

**Comment by Palid** [comment] 2016-11-14 12:37
The CPU usage is resolved with your new binary, but could you please release the source code? We can't even help you if the code is one year old. :(

**Comment by abhishekbanthia** [comment] 2016-11-19 03:53
@Palid The code here is up-to-date with the latest AppStore version. Usually, my policy is to commit working changes, but if you want to play around with my recent stuff, I'd be happy to do that.

**Comment by abhishekbanthia** [comment] 2016-11-19 03:54
And guys, sorry for the delay, the new version will be up as soon as my internship ends i.e. by the 2nd week of December.

**Comment by abdonrd** [comment] 2017-01-10 09:25
It is already fixed?

**Comment by abhishekbanthia** [comment] 2017-01-17 11:32
Thew new update should fix the issue. 

Here's the update link: https://itunes.apple.com/us/app/clocker-menubar-world-clock/id1056643111?mt=12

Closing.

**Closed by abhishekbanthia** 2017-01-17 11:32 UTC
Labels: bug

**Comment by rootux** [comment] 2019-11-22 16:22
I still got this issue on the latest clocker
