### ISSUE TITLE
Vertical Scroll Bar covers times

### ISSUE THREAD

**Issue by IkonOne** [abhishekbanthia/Clocker#23] opened 2017-05-30 13:01 UTC
MacBook Air (13-inch, Mid 2013)
OSX 10.12.5

As stated, the vertical scroll bar in the when Clocker is attached to the menu bar covers part of the times.  This issue is not present in floating mode.

Or maybe it isn't a vertical scroll bar?

![screen shot 2017-05-30 at 6 57 40 am](https://cloud.githubusercontent.com/assets/1105646/26584329/ab5cb3e8-4505-11e7-8c4c-51dcdbb24c70.png)

**Comment by abhishekbanthia** [comment] 2017-05-30 14:37
Hi @IkonOne, thanks for reporting. This seems to be an issue with the black theme. Looking into this.

**Comment by IkonOne** [comment] 2017-05-30 17:40
Thank you @abhishekbanthia  It appears to be an issue with the default theme as well by the way.

![screen shot 2017-05-30 at 11 39 46 am](https://cloud.githubusercontent.com/assets/1105646/26596685/cb1cda7e-452c-11e7-9e38-0892e5ed8670.png)

**Comment by abhishekbanthia** [comment] 2017-05-30 18:08
Yikes; similar to #20.

**Comment by IkonOne** [comment] 2017-05-30 22:48
Oh, I didn't realize there was already an issue for this.  I'll close this one and reference it in the other issue.

**Comment by IkonOne** [comment] 2017-05-30 22:49
It looks like you closed the other issue...

**Comment by abhishekbanthia** [comment] 2017-05-31 00:14
I'm unable to reproduce it in the latest version :( . Are you using multiple monitors?

**Comment by abhishekbanthia** [comment] 2017-05-31 17:53
hey @IkonOne, i'm uploading a version which I believe fixes the issues. Can you try it and let me know? Thanks. FYI: You might need to add your timezones again.

[Uploading Clocker.app.zip…]()

**Comment by abhishekbanthia** [comment] 2017-06-01 16:05
[Clocker.app.zip](https://github.com/abhishekbanthia/Clocker/files/1045377/Clocker.app.zip)

**Comment by ryangum** [comment] 2017-06-02 13:29
That fixed it for me!

**Comment by abhishekbanthia** [comment] 2017-07-16 16:22
Guys, any of you have the system preference to always show scroll bars?

<img width="655" alt="screen shot 2017-07-16 at 11 22 24 am" src="https://user-images.githubusercontent.com/8280282/28249313-14932882-6a19-11e7-9757-9118d1875163.png">

**Comment by IkonOne** [comment] 2017-07-18 21:22
No.  It is set to 'Automatically based on mouse or trackpad' on my end.

On Sun, Jul 16, 2017 at 11:22 AM, Abhishek Banthia <notifications@github.com

**Comment by abhishekbanthia** [comment] 2017-07-26 14:48
The new version is out which should fix this issue. Closing...

**Closed by abhishekbanthia** 2017-07-26 14:48 UTC
