### ISSUE TITLE
When clicking on Clocker icon, icon disappears and seems to have crashed

### ISSUE THREAD

**Issue by russelltrafford** [abhishekbanthia/Clocker#15] opened 2017-01-17 16:47 UTC
I just removed the unsigned versions now that the app store has been updated, and installed the official one from the App Store.

When I run the app, it appears in the taskbar, but as soon as I click on the icon, it disappears leading me to believe it has crashed as I then open the app again and it re-appears, but crashes again on click of the icon.

This happens both when I have my 2 external monitors plugged in as well as when I unplug the external monitors and just use my Macbook Pro screen.

**Comment by abhishekbanthia** [comment] 2017-01-17 17:20
Ah; that's bad. Can you attach your console logs if thats not much of a hassle for you?

**Comment by russelltrafford** [comment] 2017-01-17 17:25
Sure, but hmmm, how do I get the console logs?

**Comment by abhishekbanthia** [comment] 2017-01-17 17:30
1. Launch the Console application (from the Utilities folder inside your Applications folder).
2. Click the leftmost button in the toolbar to show the sidebar, if it’s hidden.
3. Select All Messages in the tab bar.
4. If the Activities button in the toolbar is enabled with a blue icon, click it to turn this off.
5. Switch back to the Clocker app, and try to trigger the issue. This will (hopefully!) print some output to the Console.
6. Return to the Console, and select the recent error messages from the main window, or from the Menu Bar choose Edit ▸ Select All.
7. From the Menu Bar, choose Edit ▸ Copy. Then, open the TextEdit application and Paste the copied logs into a new plain text document.
8. Save the text document in .txt format, and attach this to the issue!

**Comment by abhishekbanthia** [comment] 2017-01-20 23:07
Hi @russelltrafford, you can also try clearing your Clocker defaults by executing the following command in your terminal:

_defaults delete com.abhishek.Clocker_

You'll need to start the app again. Let me know if this works.

**Comment by russelltrafford** [comment] 2017-01-20 23:29
Sorry for the delay. The command cleared the defaults, but did not solve the issue. Heres the logs:

2017-01-20 3:26:48.385 PM com.apple.xpc.launchd[1]: (com.abhishek.Clocker.233312[90944]) Service exited due to signal: Illegal instruction: 4
2017-01-20 3:26:48.400 PM com.apple.xpc.launchd[1]: (com.apple.ReportCrash[90960]) Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.ReportCrash
2017-01-20 3:26:48.701 PM ReportCrash[90960]: Saved crash report for Clocker[90944] version 1.4 (25) to /Users/my.user/Library/Logs/DiagnosticReports/Clocker_2017-01-20-152648_MyMachine.crash

For the actual crash report, I can send it to you by email rather than posting here, in case it contains personal machine details.

**Comment by abhishekbanthia** [comment] 2017-01-20 23:34
Sure, you can mail me [here](mailto:abhishekbanthia@me.com).

**Comment by russelltrafford** [comment] 2017-01-20 23:35
Cheers, I only have your @apple.com ID, I assume you longer have that?

**Comment by abhishekbanthia** [comment] 2017-01-20 23:36
I don't; since my internship ended :)

**Comment by EdZava** [comment] 2017-01-27 14:34
I have the same problem. 
It can be fixed?

**Comment by abhishekbanthia** [comment] 2017-01-27 14:36
I'm currently working on the problem. You can rollback to an unsigned version of the release which many people have reported to be working. I have attached the release to the comment here:

https://github.com/abhishekbanthia/Clocker/issues/8#issuecomment-258552442

**Comment by markandrewj** [comment] 2017-01-29 03:45
Just wanted to say I have been having the same issue.

**Comment by russelltrafford** [comment] 2017-02-23 22:22
No rush for me, but just to say im still getting this issue.

**Comment by abhishekbanthia** [comment] 2017-03-13 23:59
Hey @russelltrafford, @markandrewj are you by using a custom date format?

**Comment by russelltrafford** [comment] 2017-03-14 00:10
Nope, dont think so? dont even know what that is.

**Comment by zawarudo** [comment] 2017-04-17 12:44
@abhishekbanthia

Getting this issue when I upgraded to macOS Sierra,
getting the same crash as noted above.

Cleared preferences with `defaults delete com.abhishek.Clocker`
which did fix the problem.

However adding a time zone made it crash again.

Attempted to grab relevant logs from console but the errors only show up as <private> messages

![image](https://cloud.githubusercontent.com/assets/2955134/25089257/10760dd0-23b7-11e7-9044-54b2ca6b9eb4.png)

**Comment by abhishekbanthia** [comment] 2017-04-17 13:50
Thank you for reporting the issue, @zawarudo. I assume, you're not using any custom time and date format?

<img width="780" alt="screen shot 2017-04-17 at 09 53 43" src="https://cloud.githubusercontent.com/assets/8280282/25090787/56e84012-2353-11e7-8f62-97a3e9f48ff1.png">

**Comment by zawarudo** [comment] 2017-04-17 13:54
I did not change anything before or after updating OSX, here is what I have.

![image](https://cloud.githubusercontent.com/assets/2955134/25090879/bf707a88-23c0-11e7-97ba-c3181ddeeaf4.png)

**Comment by abhishekbanthia** [comment] 2017-04-17 16:31
Are you on macOS 10.12.1?

**Comment by markandrewj** [comment] 2017-04-20 02:14
Hey, sorry for the late reply, I am not using a custom time format as far as I know. I am using macOS 10.12.4.

**Comment by zawarudo** [comment] 2017-04-20 02:17
Also on macOS 10.12.4

**Comment by abhishekbanthia** [comment] 2017-04-21 17:05
Thanks for the reply! quick question: are you guys based out of US?

**Comment by zawarudo** [comment] 2017-04-21 17:16
@abhishekbanthia I am, 

funny enough while trying to take a screenshot of the language and region option

![image](https://cloud.githubusercontent.com/assets/2955134/25288726/99e77bf6-2701-11e7-9c6d-41274dee2d49.png)

for you I realized it had an extra language for german in there which is strange because I only ever do english and japanese.

Once I removed it my clocker works perfectly.

**Comment by markandrewj** [comment] 2017-04-21 22:46
I am in Canada. 
![screen shot 2017-04-21 at 4 43 58 pm](https://cloud.githubusercontent.com/assets/142597/25298442/fbee6512-26b1-11e7-90e3-fbfc87b1ae38.png)

**Comment by russelltrafford** [comment] 2017-04-24 17:15
I'm in Canada. BC. PST Timezone.

**Comment by abhishekbanthia** [comment] 2017-04-27 23:19
Well. If the issue is what I think it is, the attached build should fix the crashes. Let me know how it goes.


[Clocker.app.zip](https://github.com/abhishekbanthia/Clocker/files/963126/Clocker.app.zip)

**Comment by markandrewj** [comment] 2017-04-28 02:10
Hey, the new settings look nice. This did fix the crashing issue. However, I am on a dual monitor, and it always opens the the panel in the top right of my left (second) monitor. I also miss being able to have it in a mode with just the clock icon. Thanks for working on this, I know it's just a pet project, but I enjoy that this is small world view clock with out bloat.

**Comment by abhishekbanthia** [comment] 2017-04-28 02:38
@markandrewj if you don't have any favourites, you should see the clock icon in the menubar. Also, fix for multiple monitors is next on my list. :)

<img width="582" alt="screen shot 2017-04-28 at 12 06 58 am" src="https://cloud.githubusercontent.com/assets/8280282/25512219/a3a67026-2ba6-11e7-8487-333ca3825492.png">

**Comment by markandrewj** [comment] 2017-04-30 03:26
Awesome :)

**Comment by abhishekbanthia** [comment] 2017-05-02 01:04
Hi @markandrewj, the new version attempts to fix the monitor issue. Let me know how it goes.

**Comment by markandrewj** [comment] 2017-05-02 12:02
Seems to be working, thanks :)

**Comment by abhishekbanthia** [comment] 2017-05-02 13:07
Guys, new version is out which should fix the crashing issue. Closing this for now.

**Closed by abhishekbanthia** 2017-05-02 13:07 UTC
