### ISSUE TITLE
Hotkey doesn't work until you go into preferences

### ISSUE THREAD

**Issue by peterdalydickson** [abhishekbanthia/Clocker#27] opened 2017-07-12 12:56 UTC
I have ⌘F12 set as the hotkey to open Clocker.

However, after starting Clocker, ⌘F12 only works after I click the cog to open preferences.

**Comment by abhishekbanthia** [comment] 2017-07-12 14:32
Looking into it.

**Comment by abhishekbanthia** [comment] 2017-07-16 16:35
That's easily reproducible. The issue is with the shortcut observer not starting when you restart Clocker.

**Comment by abhishekbanthia** [comment] 2017-07-26 14:48
Hi @peterdalydickson, the new version is out now which should fix this issue. Closing..

**Closed by abhishekbanthia** 2017-07-26 14:48 UTC
